2022-11-06 15:18:10.827 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-06 15:18:10.831 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration climate_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-06 15:18:11.208 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface
2022-11-06 15:18:23.388 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Fire' for fully_kiosk integration not ready yet: Cannot connect to host 192.168.86.37:2323 ssl:default [Connect call failed ('192.168.86.37', 2323)]; Retrying in background
2022-11-06 15:18:24.206 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2022-11-06 15:18:24.219 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
    time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'
2022-11-06 15:18:48.169 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:18:48.283 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2022-11-06 15:18:51.248 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:24:38.843 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities automation.set_climate_entities_temp or it is/they are currently not available
2022-11-06 15:24:38.864 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:25:19.293 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities automation.set_climate_entities_temp or it is/they are currently not available
2022-11-06 15:29:06.640 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/restart request
